# Generated by Django 5.2.8 on 2026-01-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('sex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_color', models.TextField()),
                ('band_number', models.PositiveSmallIntegerField()),
                ('breed', models.TextField()),
                ('mature_age', models.PositiveSmallIntegerField()),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_data', to='stock.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='MRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MRO_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lay_date', models.DateField()),
                ('condition', models.TextField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_data', to='stock.stock')),
            ],
        ),
    ]
