# Generated by Django 5.2.8 on 2026-01-23 18:50
import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('dod', models.DateField(blank=True, null=True)),
                ('sex', models.TextField()),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_color', models.TextField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.breed')),
                ('livestock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_data', to='stock.livestock')),
                ('band_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='MRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MRO_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_date', models.DateField()),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lay_date', models.DateField()),
                ('condition', models.TextField(blank=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egg_data', to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Hatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('equipment', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('eggs_started', models.PositiveSmallIntegerField()),
                ('eggs_hatched', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_hatch_date', models.DateField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.breed')),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mature_age', models.PositiveSmallIntegerField()),
                ('eggs_per_year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
