# Generated by Django 5.2.8 on 2026-01-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_id_alter_stock_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_data', to='stock.stock'),
            preserve_default=False,
        ),
    ]
