# Generated by Django 5.2.8 on 2026-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_livestock_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='dod',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='dob',
            field=models.DateField(),
        ),
    ]
