# Generated by Django 5.2.8 on 2026-01-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_livestock_dod_alter_livestock_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
