# Generated by Django 5.2.8 on 2026-01-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_livestock_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_data', to='stock.livestock'),
        ),
    ]
