# Generated by Django 5.2.8 on 2026-01-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_chicken_livestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='livestock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_data', to='stock.livestock'),
        ),
        migrations.AlterField(
            model_name='egg',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egg_data', to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='finishedgoods',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods_data', to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_data', to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='mro',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MRO_data', to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_data', to='stock.stock'),
        ),
    ]
