# Generated by Django 5.2.8 on 2026-01-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_chicken_livestock_alter_egg_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('equipment', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('eggs_started', models.PositiveSmallIntegerField()),
                ('eggs_hatched', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_hatch_date', models.DateField(blank=True, null=True)),
                ('breed', models.TextField()),
            ],
        ),
    ]
