# Generated by Django 5.2.8 on 2026-01-24 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_hatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mature_age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chicken',
            name='mature_age',
        ),
        migrations.AddField(
            model_name='hatch',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='band_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.breed'),
        ),
        migrations.AlterField(
            model_name='hatch',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.breed'),
        ),
    ]
