# Generated by Django 5.2.8 on 2026-01-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_breed_remove_chicken_mature_age_hatch_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='eggs_per_year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
