# Generated by Django 5.2.8 on 2025-11-26 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_created', models.DateField(null=True)),
                ('width', models.PositiveSmallIntegerField()),
                ('length', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.PositiveSmallIntegerField()),
                ('position_x', models.PositiveSmallIntegerField()),
                ('position_y', models.PositiveSmallIntegerField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.bed')),
            ],
        ),
    ]
